import { iniciarCarousel } from "./modules/carousel.js";
import { iniciarFAQ } from "./modules/faq.js";
import { iniciarMenu } from "./modules/menu-mobile.js";
import { iniciarScrollSuave } from "./modules/scroll.js";
import { iniciarAnimacoes } from "./modules/animations.js";
import { iniciarDarkMode } from "./modules/darkMode.js";
import { iniciarCart } from "./modules/cart.js";
import { iniciarProdutos } from "./modules/products.js";
import { iniciarCheckout } from "./modules/checkout.js";
import { iniciarGaleria } from "./modules/gallery.js";
import { iniciarScrollTop } from "./modules/scrollTop.js";
import { iniciarBlog } from "./modules/blog.js";
import { iniciarMapa } from "./modules/map.js";
import { iniciarPesquisa } from "./modules/search.js";

iniciarCarousel();
iniciarFAQ();
iniciarMenu();
iniciarScrollSuave();
iniciarDarkMode();
iniciarCart();
iniciarProdutos();
iniciarAnimacoes();
iniciarCheckout();
iniciarGaleria();
iniciarScrollTop();
iniciarBlog();
iniciarMapa();
iniciarPesquisa();
